version: '3'

services:
  api:
    container_name: northrend-api
    build: .
    ports:
      - "5000:5000"
    networks:
      - northrend-net
    depends_on:
      - northrend-mongo
  northrend-mongo:
    image: mongo
    restart: always
    networks:
      - northrend-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  northrend-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - northrend-net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@northrend-mongo:27017/

volumes:
  mongo-volume:

networks:
  northrend-net:
    driver: bridge